import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    appName: 'قياساتي',
    calorieCalculator: 'حاسبة السعرات الحرارية',
    bodyMeasurements: 'قياسات الجسم',
    cardioConverter: 'محول الكارديو',
    age: 'العمر',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    weight: 'الوزن (كيلو)',
    height: 'الطول (سم)',
    activityLevel: 'مستوى النشاط',
    sedentary: 'قليل الحركة',
    lightlyActive: 'نشاط خفيف',
    moderatelyActive: 'نشاط متوسط',
    veryActive: 'نشاط عالي',
    extraActive: 'نشاط عالي جداً',
    calculate: 'احسب',
    bmr: 'معدل الأيض الأساسي',
    tdee: 'إجمالي استهلاك الطاقة اليومي',
    calories: 'سعرة حرارية',
    startTracking: 'ابدأ التتبع',
    yourHealthGuide: 'دليلك الصحي الشامل',
    trackCalories: 'لحساب السعرات الحرارية وتتبع قياسات الجسم وتحويل السعرات لدقائق التمارين',
    
    // My Items
    myItems: 'أغراضي',
    myItemsDesc: 'تحقق من أغراض التمرين قبل الذهاب وبعد العودة',
    exploreItems: 'استكشف أغراضي',
    beforeWorkout: 'قبل التمرين',
    afterWorkout: 'بعد التمرين',
    addNewItem: 'إضافة غرض جديد',
    itemName: 'اسم الغرض',
    selectIcon: 'اختر أيقونة',
    add: 'إضافة',
    cancel: 'إلغاء',
    delete: 'حذف',
    checkAll: 'تحقق من الكل',
    uncheckAll: 'إلغاء تحديد الكل',
    noItemsYet: 'لا توجد أغراض بعد',
    addFirstItem: 'أضف أول غرض لك',
    workoutReminder: 'تذكير التمرين',
    enableNotifications: 'تفعيل الإشعارات',
    setWorkoutTime: 'حدد وقت التمرين',
    reminderBefore: 'تذكير قبل التمرين (دقيقة)',
    reminderAfter: 'تذكير بعد التمرين (دقيقة)',
    save: 'حفظ',
    beforeWorkoutDesc: 'تأكد من جميع أغراضك قبل الذهاب للتمرين',
    afterWorkoutDesc: 'تأكد من استرداد جميع أغراضك بعد التمرين',
    
    // Body Measurements
    neck: 'الرقبة (سم)',
    shoulders: 'الأكتاف (سم)',
    chest: 'الصدر (سم)',
    rightArm: 'الذراع الأيمن (سم)',
    leftArm: 'الذراع الأيسر (سم)',
    abdomen: 'البطن (سم)',
    waist: 'الخصر (سم)',
    rightThigh: 'الفخذ الأيمن (سم)',
    leftThigh: 'الفخذ الأيسر (سم)',
    rightLeg: 'الساق الأيمن (سم)',
    leftLeg: 'الساق الأيسر (سم)',
    addMeasurement: 'أضف قياس جديد',
    saveMeasurement: 'احفظ القياس',
    measurementSaved: 'تم حفظ القياس بنجاح!',
    noMeasurements: 'لا توجد قياسات محفوظة',
    measurementHistory: 'تاريخ القياسات',
    viewProgress: 'عرض التقدم',
    date: 'التاريخ',
    measurement: 'القياس',
    progress: 'التقدم',
    cm: 'سم',
    
    // Bodybuilding specific measurements
    arms: 'الذراعين (سم)',
    calves: 'السمانة (سم)', 
    thighs: 'الفخذين (سم)',
    back: 'الظهر (سم)',
    
    // New measurement type labels
    selectMeasurementType: 'اختر نوع القياسات',
    generalMeasurements: 'قياسات عامة',
    generalMeasurementsDesc: 'لإنقاص الوزن والمتابعة العامة',
    bodybuildingMeasurements: 'قياسات كمال الأجسام', 
    bodybuildingMeasurementsDesc: 'للاعبي كمال الأجسام والبناء العضلي',
    generalMeasurementsTitle: 'القياسات العامة',
    bodybuildingMeasurementsTitle: 'قياسات كمال الأجسام',
    measurementPlaceholder: 'سم',
    bodybuildingType: 'كمال أجسام',
    generalType: 'عامة',
    measurementCount: 'قياسات',
    trackBodyMeasurements: 'تتبع قياسات الجسم',
    trackBodyMeasurementsDesc: 'سجل وتتبع قياساتك في جميع المناطق الرئيسية',
    
    // Cardio Converter
    caloriesInput: 'عدد السعرات المراد حرقها',
    exerciseType: 'نوع التمرين',
    running: 'الجري',
    cycling: 'ركوب الدراجة',
    swimming: 'السباحة',
    walking: 'المشي',
    jumpingRope: 'نط الحبل',
    rowing: 'التجديف',
    convert: 'تحويل',
    timeNeeded: 'الوقت المطلوب',
    minutes: 'دقيقة',
    selectExercise: 'اختر نوع التمرين',
    enterCalories: 'أدخل عدد السعرات',
    backToHome: 'العودة للرئيسية',
    explore: 'استكشف',
    getStarted: 'ابدأ الآن',
    trackMyHealth: 'تتبع صحتي',
    
    // Weekly Program
    weeklyProgram: 'البرنامج الأسبوعي',
    createProgram: 'إنشاء برنامج',
    myPrograms: 'برامجي',
    programName: 'اسم البرنامج',
    dayOfWeek: 'يوم الأسبوع',
    exerciseName: 'اسم التمرين',
    sets: 'المجموعات',
    reps: 'التكرارات',
    exerciseWeight: 'الوزن',
    notes: 'ملاحظات',
    addExercise: 'إضافة تمرين',
    saveProgram: 'حفظ البرنامج',
    programSaved: 'تم حفظ البرنامج بنجاح!',
    noPrograms: 'لا توجد برامج محفوظة',
    editProgram: 'تعديل البرنامج',
    deleteProgram: 'حذف البرنامج',
    confirmDelete: 'هل أنت متأكد من حذف هذا البرنامج؟',
    sunday: 'الأحد',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    rest: 'راحة',
    
    // Wake-up Challenge
    wakeUpChallenge: 'تحدي الاستيقاظ',
    setupChallenge: 'إعداد التحدي',
    tracking: 'التتبع',
    statistics: 'الإحصائيات',
    wakeUpTime: 'وقت الاستيقاظ',
    challengeDuration: 'مدة التحدي (أيام)',
    startChallenge: 'ابدأ التحدي',
    activeChallenge: 'التحدي النشط',
    targetWakeTime: 'وقت الاستيقاظ المحدد',
    today: 'اليوم',
    target: 'الهدف',
    wokeUp: 'الاستيقاظ',
    imAwake: 'أنا استيقظت',
    done: 'تم',
    pending: 'في الانتظار',
    endChallenge: 'إنهاء التحدي',
    dailyRecords: 'سجل الأيام',
    noActiveChallenge: 'لا يوجد تحدي نشط',
    setupNewChallenge: 'ابدأ تحدي جديد لتتبع استيقاظك',
    totalDays: 'إجمالي الأيام',
    successfulDays: 'أيام ناجحة',
    successRate: 'معدل النجاح',
    achievementLevel: 'مستوى الإنجاز',
    excellent: 'ممتاز',
    good: 'جيد',
    average: 'متوسط',
    needsImprovement: 'يحتاج تحسين',
    challengeSummary: 'ملخص التحدي',
    challengePeriod: 'فترة التحدي',
    days: 'أيام',
    overallProgress: 'التقدم الإجمالي',
    noStatistics: 'لا توجد إحصائيات',
    completeChallenge: 'أكمل تحدي للحصول على الإحصائيات',
    challengeStarted: 'بدأ التحدي!',
    challengeStartedDesc: 'تم بدء تحدي الاستيقاظ بنجاح',
    recorded: 'تم التسجيل!',
    recordedDesc: 'تم تسجيل وقت استيقاظك بنجاح',
    challengeEnded: 'انتهى التحدي!',
    challengeEndedDesc: 'انتهى التحدي، تحقق من إحصائياتك',
    
    // Terms and Privacy
    termsAndPrivacy: 'الشروط والخصوصية',
    termsAndPrivacyDesc: 'اقرأ شروط الاستخدام وسياسة الخصوصية للتطبيق',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    acceptanceOfTerms: 'قبول الشروط',
    acceptanceOfTermsText: 'باستخدام تطبيق "qiyasat"، فإنك توافق على الالتزام بجميع الشروط والأحكام المذكورة هنا. إذا كنت لا توافق على أي من هذه الشروط، يرجى عدم استخدام التطبيق.',
    serviceDescription: 'وصف الخدمة',
    serviceDescriptionText: 'تطبيق "qiyasat" هو أداة مساعدة لتتبع الصحة واللياقة البدنية تتضمن حاسبة السعرات الحرارية، قياسات الجسم، محول الكارديو، البرامج الأسبوعية، وتتبع الأغراض الرياضية.',
    userResponsibilities: 'مسؤوليات المستخدم',
    userResponsibilitiesText: 'كمستخدم لهذا التطبيق، فإنك توافق على:',
    userResp1: 'استخدام التطبيق للأغراض الشخصية والصحية فقط',
    userResp2: 'عدم مشاركة معلوماتك الشخصية مع أطراف ثالثة',
    userResp3: 'الحفاظ على دقة المعلومات التي تدخلها',
    userResp4: 'عدم استخدام التطبيق لأغراض غير قانونية أو ضارة',
    limitations: 'القيود والحدود',
    limitationsText: 'هذا التطبيق مخصص للأغراض المعلوماتية والتتبع الشخصي فقط. النتائج المقدمة هي تقديرات عامة وقد لا تناسب جميع الحالات الصحية الفردية.',
    medicalDisclaimer: 'إخلاء المسؤولية الطبية',
    important: 'مهم:',
    medicalDisclaimerText: 'هذا التطبيق ليس بديلاً عن الاستشارة الطبية المهنية أو التشخيص أو العلاج. استشر دائماً طبيبك أو مختص الرعاية الصحية قبل البدء في أي برنامج تمارين أو نظام غذائي جديد.',
    modifications: 'التعديلات',
    modificationsText: 'نحتفظ بالحق في تعديل هذه الشروط في أي وقت. سيتم إشعار المستخدمين بأي تغييرات جوهرية من خلال التطبيق.',
    dataCollection: 'جمع البيانات',
    dataCollectionText: 'نحن نجمع ونخزن البيانات التالية محلياً على جهازك فقط:',
    dataType1: 'المعلومات الشخصية (العمر، الجنس، الوزن، الطول)',
    dataType2: 'قياسات الجسم والتقدم',
    dataType3: 'تفضيلات التطبيق (اللغة، السمة)',
    dataType4: 'سجلات التمارين والأنشطة',
    dataUsage: 'استخدام البيانات',
    dataUsageText: 'نستخدم بياناتك لـ:',
    dataUsage1: 'حساب السعرات الحرارية والقيم الغذائية',
    dataUsage2: 'تتبع تقدمك الشخصي',
    dataUsage3: 'تخصيص تجربة التطبيق',
    dataUsage4: 'حفظ تفضيلاتك وإعداداتك',
    dataSecurity: 'أمان البيانات',
    dataSecurityText: 'جميع بياناتك محفوظة محلياً على جهازك باستخدام تقنية Local Storage الآمنة. نحن لا نرسل أو نشارك أي من بياناتك الشخصية مع خوادم خارجية أو أطراف ثالثة.',
    localStorage: 'التخزين المحلي',
    importantNote: 'ملاحظة مهمة:',
    localStorageText: 'جميع بياناتك محفوظة محلياً على متصفحك. إذا قمت بمسح بيانات المتصفح أو إلغاء تثبيت التطبيق، ستفقد جميع بياناتك المحفوظة. ننصح بعمل نسخة احتياطية من بياناتك المهمة.',
    thirdParties: 'الأطراف الثالثة',
    thirdPartiesText: 'نحن لا نشارك بياناتك مع أي أطراف ثالثة. التطبيق يعمل بشكل مستقل ولا يتطلب اتصالاً بالإنترنت للوظائف الأساسية.',
    userRights: 'حقوق المستخدم',
    userRightsText: 'كمستخدم، لديك الحق في:',
    userRight1: 'الوصول إلى جميع بياناتك المحفوظة',
    userRight2: 'تعديل أو حذف أي من بياناتك',
    userRight3: 'تصدير بياناتك (عبر ميزات المتصفح)',
    userRight4: 'إيقاف استخدام التطبيق في أي وقت',
    lastUpdated: 'آخر تحديث',
    lastUpdatedDate: '20 أغسطس 2024',
    contactInfo: 'للاستفسارات: تواصل معنا عبر التطبيق',
    
    // Water Calculator
    waterCalculator: 'حاسبة الماء',
    waterCalculatorDesc: 'احسب كمية الماء التي تحتاجها يومياً حسب وزنك ونشاطك البدني',
    waterNeedsCalculator: 'حاسبة احتياجك من الماء',
    waterNeedsCalculatorDesc: 'أدخل وزنك وساعات التمرين لحساب احتياجك اليومي من الماء',
    weightKg: 'الوزن (كيلوغرام)',
    enterWeight: 'أدخل وزنك',
    dailyExerciseHours: 'ساعات التمرين اليومية',
    enterExerciseHours: 'أدخل ساعات التمرين',
    reset: 'إعادة تعيين',
    yourDailyWaterIntake: 'احتياجك اليومي من الماء',
    ml: 'مل',
    glassesApprox: 'كوب تقريباً (250 مل لكل كوب)',
    note: 'ملاحظة:',
    waterNote: 'هذه حاسبة تقديرية. قد تحتاج المزيد من الماء في الطقس الحار أو عند المرض.',
    urineColorGuide: 'دليل لون البول',
    urineColorGuideDesc: 'تحقق من حالة الترطيب من خلال لون البول',
    clearVeryLightYellow: 'شفاف/أصفر فاتح جداً',
    excellentOptimalHydration: 'ممتاز - ترطيب مثالي',
    lightYellow: 'أصفر فاتح',
    goodAdequateHydration: 'جيد - ترطيب كافي',
    mediumYellow: 'أصفر متوسط',
    drinkMoreWater: 'اشرب المزيد من الماء',
    darkYellow: 'أصفر داكن',
    mildDehydration: 'جفاف خفيف - اشرب الماء فوراً',
    brownOrange: 'بني/برتقالي',
    severeDehydration: 'جفاف شديد - استشر طبيب',
    hydrationTips: 'نصائح للترطيب الأمثل:',
    hydrationTip1: 'اشرب الماء على مدار اليوم',
    hydrationTip2: 'اشرب المزيد قبل وأثناء وبعد التمرين',
    hydrationTip3: 'اشرب المزيد في الطقس الحار',
    hydrationTip4: 'قلل من الكافيين والكحول',
    invalidWeight: 'يرجى إدخال وزن صحيح (1-500 كغ)',
    invalidExercise: 'يرجى إدخال ساعات تمرين صحيحة (0-24 ساعة)'
  },
  en: {
    appName: 'QiyasaT',
    calorieCalculator: 'Calorie Calculator',
    bodyMeasurements: 'Body Measurements',
    cardioConverter: 'Cardio Converter',
    age: 'Age',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    weight: 'Weight (kg)',
    height: 'Height (cm)',
    activityLevel: 'Activity Level',
    sedentary: 'Sedentary (little/no exercise)',
    lightlyActive: 'Lightly active (light exercise)',
    moderatelyActive: 'Moderately active (moderate exercise)',
    veryActive: 'Very active (hard exercise)',
    extraActive: 'Extra active (very hard exercise)',
    calculate: 'Calculate',
    bmr: 'Basal Metabolic Rate',
    tdee: 'Total Daily Energy Expenditure',
    calories: 'calories',
    startTracking: 'Start Tracking',
    yourHealthGuide: 'Your Complete Health Guide',
    trackCalories: 'Calculate calories, track body measurements, and convert calories to exercise minutes',
    
    // My Items
    myItems: 'My Items',
    myItemsDesc: 'Check workout items before going and after returning',
    exploreItems: 'Explore My Items',
    beforeWorkout: 'Before Workout',
    afterWorkout: 'After Workout',
    addNewItem: 'Add New Item',
    itemName: 'Item Name',
    selectIcon: 'Select Icon',
    add: 'Add',
    cancel: 'Cancel',
    delete: 'Delete',
    checkAll: 'Check All',
    uncheckAll: 'Uncheck All',
    noItemsYet: 'No items yet',
    addFirstItem: 'Add your first item',
    workoutReminder: 'Workout Reminder',
    enableNotifications: 'Enable Notifications',
    setWorkoutTime: 'Set Workout Time',
    reminderBefore: 'Reminder before workout (minutes)',
    reminderAfter: 'Reminder after workout (minutes)',
    save: 'Save',
    beforeWorkoutDesc: 'Make sure you have all your items before going to workout',
    afterWorkoutDesc: 'Make sure to retrieve all your items after workout',
    
    // Body Measurements
    neck: 'Neck (cm)',
    shoulders: 'Shoulders (cm)',
    chest: 'Chest (cm)',
    rightArm: 'Right Arm (cm)',
    leftArm: 'Left Arm (cm)',
    abdomen: 'Abdomen (cm)',
    waist: 'Waist (cm)',
    rightThigh: 'Right Thigh (cm)',
    leftThigh: 'Left Thigh (cm)',
    rightLeg: 'Right Leg (cm)',
    leftLeg: 'Left Leg (cm)',
    addMeasurement: 'Add New Measurement',
    saveMeasurement: 'Save Measurement',
    measurementSaved: 'Measurement saved successfully!',
    noMeasurements: 'No measurements saved',
    measurementHistory: 'Measurement History',
    viewProgress: 'View Progress',
    date: 'Date',
    measurement: 'Measurement',
    progress: 'Progress',
    cm: 'cm',
    
    // Bodybuilding specific measurements
    arms: 'Arms (cm)',
    calves: 'Calves (cm)',
    thighs: 'Thighs (cm)', 
    back: 'Back (cm)',
    
    // New measurement type labels
    selectMeasurementType: 'Select Measurement Type',
    generalMeasurements: 'General Measurements',
    generalMeasurementsDesc: 'For weight loss and general tracking',
    bodybuildingMeasurements: 'Bodybuilding Measurements',
    bodybuildingMeasurementsDesc: 'For bodybuilders and muscle building',
    generalMeasurementsTitle: 'General Measurements',
    bodybuildingMeasurementsTitle: 'Bodybuilding Measurements',
    measurementPlaceholder: 'cm',
    bodybuildingType: 'Bodybuilding',
    generalType: 'General',
    measurementCount: 'measurements',
    trackBodyMeasurements: 'Track Body Measurements',
    trackBodyMeasurementsDesc: 'Record and track your measurements in all key areas',
    
    // Cardio Converter
    caloriesInput: 'Calories to burn',
    exerciseType: 'Exercise type',
    running: 'Running',
    cycling: 'Cycling',
    swimming: 'Swimming',
    walking: 'Walking',
    jumpingRope: 'Jumping rope',
    rowing: 'Rowing',
    convert: 'Convert',
    timeNeeded: 'Time needed',
    minutes: 'minutes',
    selectExercise: 'Select exercise type',
    enterCalories: 'Enter calories',
    backToHome: 'Back to Home',
    explore: 'Explore',
    getStarted: 'Get Started',
    trackMyHealth: 'Track My Health',
    
    // Weekly Program
    weeklyProgram: 'Weekly Program',
    createProgram: 'Create Program',
    myPrograms: 'My Programs',
    programName: 'Program Name',
    dayOfWeek: 'Day of Week',
    exerciseName: 'Exercise Name',
    sets: 'Sets',
    reps: 'Reps',
    exerciseWeight: 'Weight',
    notes: 'Notes',
    addExercise: 'Add Exercise',
    saveProgram: 'Save Program',
    programSaved: 'Program saved successfully!',
    noPrograms: 'No programs saved',
    editProgram: 'Edit Program',
    deleteProgram: 'Delete Program',
    confirmDelete: 'Are you sure you want to delete this program?',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    rest: 'Rest',
    
    // Wake-up Challenge
    wakeUpChallenge: 'Wake-up Challenge',
    setupChallenge: 'Setup Challenge',
    tracking: 'Tracking',
    statistics: 'Statistics',
    wakeUpTime: 'Wake-up Time',
    challengeDuration: 'Challenge Duration (days)',
    startChallenge: 'Start Challenge',
    activeChallenge: 'Active Challenge',
    targetWakeTime: 'Target wake-up time',
    today: 'Today',
    target: 'Target',
    wokeUp: 'Woke up',
    imAwake: 'I\'m Awake',
    done: 'Done',
    pending: 'Pending',
    endChallenge: 'End Challenge',
    dailyRecords: 'Daily Records',
    noActiveChallenge: 'No Active Challenge',
    setupNewChallenge: 'Start a new challenge to track your wake-up times',
    totalDays: 'Total Days',
    successfulDays: 'Successful Days',
    successRate: 'Success Rate',
    achievementLevel: 'Achievement Level',
    excellent: 'Excellent',
    good: 'Good',
    average: 'Average',
    needsImprovement: 'Needs Improvement',
    challengeSummary: 'Challenge Summary',
    challengePeriod: 'Challenge Period',
    days: 'days',
    overallProgress: 'Overall Progress',
    noStatistics: 'No Statistics Available',
    completeChallenge: 'Complete a challenge to see statistics',
    challengeStarted: 'Challenge Started!',
    challengeStartedDesc: 'Wake-up challenge started successfully',
    recorded: 'Recorded!',
    recordedDesc: 'Your wake-up time has been recorded successfully',
    challengeEnded: 'Challenge Ended!',
    challengeEndedDesc: 'Challenge ended, check your statistics',
    
    // Terms and Privacy
    termsAndPrivacy: 'Terms & Privacy',
    termsAndPrivacyDesc: 'Read the terms of service and privacy policy for the app',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    acceptanceOfTerms: 'Acceptance of Terms',
    acceptanceOfTermsText: 'By using the "Sehati" app, you agree to comply with all the terms and conditions mentioned here. If you do not agree to any of these terms, please do not use the app.',
    serviceDescription: 'Service Description',
    serviceDescriptionText: 'The "Sehati" app is a health and fitness tracking tool that includes calorie calculator, body measurements, cardio converter, weekly programs, and sports items tracking.',
    userResponsibilities: 'User Responsibilities',
    userResponsibilitiesText: 'As a user of this app, you agree to:',
    userResp1: 'Use the app for personal and health purposes only',
    userResp2: 'Not share your personal information with third parties',
    userResp3: 'Maintain accuracy of the information you enter',
    userResp4: 'Not use the app for illegal or harmful purposes',
    limitations: 'Limitations',
    limitationsText: 'This app is intended for informational and personal tracking purposes only. The results provided are general estimates and may not suit all individual health conditions.',
    medicalDisclaimer: 'Medical Disclaimer',
    important: 'Important:',
    medicalDisclaimerText: 'This app is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your doctor or healthcare professional before starting any new exercise program or diet.',
    modifications: 'Modifications',
    modificationsText: 'We reserve the right to modify these terms at any time. Users will be notified of any material changes through the app.',
    dataCollection: 'Data Collection',
    dataCollectionText: 'We collect and store the following data locally on your device only:',
    dataType1: 'Personal information (age, gender, weight, height)',
    dataType2: 'Body measurements and progress',
    dataType3: 'App preferences (language, theme)',
    dataType4: 'Exercise and activity records',
    dataUsage: 'Data Usage',
    dataUsageText: 'We use your data to:',
    dataUsage1: 'Calculate calories and nutritional values',
    dataUsage2: 'Track your personal progress',
    dataUsage3: 'Customize the app experience',
    dataUsage4: 'Save your preferences and settings',
    dataSecurity: 'Data Security',
    dataSecurityText: 'All your data is stored locally on your device using secure Local Storage technology. We do not send or share any of your personal data with external servers or third parties.',
    localStorage: 'Local Storage',
    importantNote: 'Important Note:',
    localStorageText: 'All your data is stored locally in your browser. If you clear browser data or uninstall the app, you will lose all your saved data. We recommend backing up your important data.',
    thirdParties: 'Third Parties',
    thirdPartiesText: 'We do not share your data with any third parties. The app operates independently and does not require internet connection for basic functions.',
    userRights: 'User Rights',
    userRightsText: 'As a user, you have the right to:',
    userRight1: 'Access all your saved data',
    userRight2: 'Modify or delete any of your data',
    userRight3: 'Export your data (via browser features)',
    userRight4: 'Stop using the app at any time',
    lastUpdated: 'Last Updated',
    lastUpdatedDate: 'August 20, 2024',
    contactInfo: 'For inquiries: Contact us through the app',
    
    // Water Calculator
    waterCalculator: 'Water Calculator',
    waterCalculatorDesc: 'Calculate your daily water intake based on your weight and physical activity',
    waterNeedsCalculator: 'Your Water Needs Calculator',
    waterNeedsCalculatorDesc: 'Enter your weight and exercise hours to calculate your daily water needs',
    weightKg: 'Weight (kg)',
    enterWeight: 'Enter your weight',
    dailyExerciseHours: 'Daily Exercise Hours',
    enterExerciseHours: 'Enter exercise hours',
    reset: 'Reset',
    yourDailyWaterIntake: 'Your Daily Water Intake',
    ml: 'ml',
    glassesApprox: 'glasses (250ml each)',
    note: 'Note:',
    waterNote: 'This is an estimate. You may need more water in hot weather or when sick.',
    urineColorGuide: 'Urine Color Guide',
    urineColorGuideDesc: 'Check your hydration status through urine color',
    clearVeryLightYellow: 'Clear/Very Light Yellow',
    excellentOptimalHydration: 'Excellent - Optimal Hydration',
    lightYellow: 'Light Yellow',
    goodAdequateHydration: 'Good - Adequate Hydration',
    mediumYellow: 'Medium Yellow',
    drinkMoreWater: 'Drink More Water',
    darkYellow: 'Dark Yellow',
    mildDehydration: 'Mild Dehydration - Drink Water Now',
    brownOrange: 'Brown/Orange',
    severeDehydration: 'Severe Dehydration - Consult Doctor',
    hydrationTips: 'Tips for Optimal Hydration:',
    hydrationTip1: 'Drink water throughout the day',
    hydrationTip2: 'Drink more before, during, and after exercise',
    hydrationTip3: 'Increase intake in hot weather',
    hydrationTip4: 'Limit caffeine and alcohol',
    invalidWeight: 'Please enter a valid weight (1-500 kg)',
    invalidExercise: 'Please enter valid exercise hours (0-24 hours)'
  },
  fr: {
    appName: 'QiyasaT',
    calorieCalculator: 'Calculateur de Calories',
    bodyMeasurements: 'Mesures Corporelles',
    cardioConverter: 'Convertisseur Cardio',
    age: 'Âge',
    gender: 'Genre',
    male: 'Homme',
    female: 'Femme',
    weight: 'Poids (kg)',
    height: 'Taille (cm)',
    activityLevel: 'Niveau d\'Activité',
    sedentary: 'Sédentaire (peu/pas d\'exercice)',
    lightlyActive: 'Légèrement actif (exercice léger)',
    moderatelyActive: 'Modérément actif (exercice modéré)',
    veryActive: 'Très actif (exercice intense)',
    extraActive: 'Extrêmement actif (exercice très intense)',
    calculate: 'Calculer',
    bmr: 'Métabolisme de Base',
    tdee: 'Dépense Énergétique Totale Quotidienne',
    calories: 'calories',
    startTracking: 'Commencer le Suivi',
    yourHealthGuide: 'Votre Guide Santé Complet',
    trackCalories: 'Calculer les calories, suivre les mesures corporelles et convertir les calories en minutes d\'exercice',
    
    // My Items
    myItems: 'Mes Affaires',
    myItemsDesc: 'Vérifiez vos affaires d\'entraînement avant de partir et après être revenu',
    exploreItems: 'Explorer Mes Affaires',
    beforeWorkout: 'Avant l\'Entraînement',
    afterWorkout: 'Après l\'Entraînement',
    addNewItem: 'Ajouter un Nouvel Article',
    itemName: 'Nom de l\'Article',
    selectIcon: 'Sélectionner une Icône',
    add: 'Ajouter',
    cancel: 'Annuler',
    delete: 'Supprimer',
    checkAll: 'Tout Cocher',
    uncheckAll: 'Tout Décocher',
    noItemsYet: 'Aucun article encore',
    addFirstItem: 'Ajoutez votre premier article',
    workoutReminder: 'Rappel d\'Entraînement',
    enableNotifications: 'Activer les Notifications',
    setWorkoutTime: 'Définir l\'Heure d\'Entraînement',
    reminderBefore: 'Rappel avant l\'entraînement (minutes)',
    reminderAfter: 'Rappel après l\'entraînement (minutes)',
    save: 'Sauvegarder',
    beforeWorkoutDesc: 'Assurez-vous d\'avoir tous vos articles avant d\'aller vous entraîner',
    afterWorkoutDesc: 'Assurez-vous de récupérer tous vos articles après l\'entraînement',
    
    // Body Measurements
    neck: 'Cou (cm)',
    shoulders: 'Épaules (cm)',
    chest: 'Poitrine (cm)',
    rightArm: 'Bras Droit (cm)',
    leftArm: 'Bras Gauche (cm)',
    abdomen: 'Abdomen (cm)',
    waist: 'Taille (cm)',
    rightThigh: 'Cuisse Droite (cm)',
    leftThigh: 'Cuisse Gauche (cm)',
    rightLeg: 'Jambe Droite (cm)',
    leftLeg: 'Jambe Gauche (cm)',
    addMeasurement: 'Ajouter une Nouvelle Mesure',
    saveMeasurement: 'Sauvegarder la Mesure',
    measurementSaved: 'Mesure sauvegardée avec succès !',
    noMeasurements: 'Aucune mesure sauvegardée',
    measurementHistory: 'Historique des Mesures',
    viewProgress: 'Voir les Progrès',
    date: 'Date',
    measurement: 'Mesure',
    progress: 'Progrès',
    cm: 'cm',
    
    // Bodybuilding specific measurements
    arms: 'Bras (cm)',
    calves: 'Mollets (cm)',
    thighs: 'Cuisses (cm)',
    back: 'Dos (cm)',
    
    // New measurement type labels
    selectMeasurementType: 'Sélectionner le Type de Mesures',
    generalMeasurements: 'Mesures Générales',
    generalMeasurementsDesc: 'Pour la perte de poids et le suivi général',
    bodybuildingMeasurements: 'Mesures de Bodybuilding',
    bodybuildingMeasurementsDesc: 'Pour les bodybuilders et la construction musculaire',
    generalMeasurementsTitle: 'Mesures Générales',
    bodybuildingMeasurementsTitle: 'Mesures de Bodybuilding',
    measurementPlaceholder: 'cm',
    bodybuildingType: 'Bodybuilding',
    generalType: 'Général',
    measurementCount: 'mesures',
    trackBodyMeasurements: 'Suivre les Mesures Corporelles',
    trackBodyMeasurementsDesc: 'Enregistrer et suivre vos mesures dans toutes les zones clés',
    
    // Cardio Converter
    caloriesInput: 'Calories à brûler',
    exerciseType: 'Type d\'exercice',
    running: 'Course',
    cycling: 'Cyclisme',
    swimming: 'Natation',
    walking: 'Marche',
    jumpingRope: 'Corde à sauter',
    rowing: 'Aviron',
    convert: 'Convertir',
    timeNeeded: 'Temps nécessaire',
    minutes: 'minutes',
    selectExercise: 'Sélectionner le type d\'exercice',
    enterCalories: 'Entrer les calories',
    backToHome: 'Retour à l\'Accueil',
    explore: 'Explorer',
    getStarted: 'Commencer',
    trackMyHealth: 'Suivre Ma Santé',
    
    // Weekly Program
    weeklyProgram: 'Programme Hebdomadaire',
    createProgram: 'Créer un Programme',
    myPrograms: 'Mes Programmes',
    programName: 'Nom du Programme',
    dayOfWeek: 'Jour de la Semaine',
    exerciseName: 'Nom de l\'Exercice',
    sets: 'Séries',
    reps: 'Répétitions',
    exerciseWeight: 'Poids',
    notes: 'Notes',
    addExercise: 'Ajouter un Exercice',
    saveProgram: 'Sauvegarder le Programme',
    programSaved: 'Programme sauvegardé avec succès !',
    noPrograms: 'Aucun programme sauvegardé',
    editProgram: 'Modifier le Programme',
    deleteProgram: 'Supprimer le Programme',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer ce programme ?',
    sunday: 'Dimanche',
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
    rest: 'Repos',
    
    // Wake-up Challenge
    wakeUpChallenge: 'Défi Réveil',
    setupChallenge: 'Configurer le Défi',
    tracking: 'Suivi',
    statistics: 'Statistiques',
    wakeUpTime: 'Heure de Réveil',
    challengeDuration: 'Durée du Défi (jours)',
    startChallenge: 'Commencer le Défi',
    activeChallenge: 'Défi Actif',
    targetWakeTime: 'Heure de réveil cible',
    today: 'Aujourd\'hui',
    target: 'Cible',
    wokeUp: 'Réveillé',
    imAwake: 'Je suis Réveillé',
    done: 'Terminé',
    pending: 'En Attente',
    endChallenge: 'Terminer le Défi',
    dailyRecords: 'Enregistrements Quotidiens',
    noActiveChallenge: 'Aucun Défi Actif',
    setupNewChallenge: 'Démarrer un nouveau défi pour suivre vos heures de réveil',
    totalDays: 'Jours Totaux',
    successfulDays: 'Jours Réussis',
    successRate: 'Taux de Réussite',
    achievementLevel: 'Niveau d\'Accomplissement',
    excellent: 'Excellent',
    good: 'Bon',
    average: 'Moyen',
    needsImprovement: 'Besoin d\'Amélioration',
    challengeSummary: 'Résumé du Défi',
    challengePeriod: 'Période du Défi',
    days: 'jours',
    overallProgress: 'Progrès Global',
    noStatistics: 'Aucune Statistique Disponible',
    completeChallenge: 'Terminez un défi pour voir les statistiques',
    challengeStarted: 'Défi Commencé !',
    challengeStartedDesc: 'Défi de réveil démarré avec succès',
    recorded: 'Enregistré !',
    recordedDesc: 'Votre heure de réveil a été enregistrée avec succès',
    challengeEnded: 'Défi Terminé !',
    challengeEndedDesc: 'Défi terminé, consultez vos statistiques',
    
    // Terms and Privacy
    termsAndPrivacy: 'Conditions et Confidentialité',
    termsAndPrivacyDesc: 'Lire les conditions d\'utilisation et la politique de confidentialité de l\'application',
    termsOfService: 'Conditions d\'Utilisation',
    privacyPolicy: 'Politique de Confidentialité',
    acceptanceOfTerms: 'Acceptation des Conditions',
    acceptanceOfTermsText: 'En utilisant l\'application "qiyasat", vous acceptez de vous conformer à toutes les conditions générales mentionnées ici. Si vous n\'acceptez pas l\'une de ces conditions, veuillez ne pas utiliser l\'application.',
    serviceDescription: 'Description du Service',
    serviceDescriptionText: 'L\'application "qiyasat" est un outil de suivi de la santé et de la forme physique qui comprend un calculateur de calories, des mesures corporelles, un convertisseur cardio, des programmes hebdomadaires et le suivi des articles de sport.',
    userResponsibilities: 'Responsabilités de l\'Utilisateur',
    userResponsibilitiesText: 'En tant qu\'utilisateur de cette application, vous acceptez de :',
    userResp1: 'Utiliser l\'application uniquement à des fins personnelles et de santé',
    userResp2: 'Ne pas partager vos informations personnelles avec des tiers',
    userResp3: 'Maintenir l\'exactitude des informations que vous saisissez',
    userResp4: 'Ne pas utiliser l\'application à des fins illégales ou nuisibles',
    limitations: 'Limitations',
    limitationsText: 'Cette application est destinée uniquement à des fins d\'information et de suivi personnel. Les résultats fournis sont des estimations générales et peuvent ne pas convenir à toutes les conditions de santé individuelles.',
    medicalDisclaimer: 'Avertissement Médical',
    important: 'Important :',
    medicalDisclaimerText: 'Cette application n\'est pas un substitut aux conseils médicaux professionnels, au diagnostic ou au traitement. Consultez toujours votre médecin ou professionnel de la santé avant de commencer tout nouveau programme d\'exercice ou régime alimentaire.',
    modifications: 'Modifications',
    modificationsText: 'Nous nous réservons le droit de modifier ces conditions à tout moment. Les utilisateurs seront informés de tout changement important via l\'application.',
    dataCollection: 'Collecte de Données',
    dataCollectionText: 'Nous collectons et stockons les données suivantes localement sur votre appareil uniquement :',
    dataType1: 'Informations personnelles (âge, sexe, poids, taille)',
    dataType2: 'Mesures corporelles et progrès',
    dataType3: 'Préférences de l\'application (langue, thème)',
    dataType4: 'Enregistrements d\'exercices et d\'activités',
    dataUsage: 'Utilisation des Données',
    dataUsageText: 'Nous utilisons vos données pour :',
    dataUsage1: 'Calculer les calories et les valeurs nutritionnelles',
    dataUsage2: 'Suivre vos progrès personnels',
    dataUsage3: 'Personnaliser l\'expérience de l\'application',
    dataUsage4: 'Sauvegarder vos préférences et paramètres',
    dataSecurity: 'Sécurité des Données',
    dataSecurityText: 'Toutes vos données sont stockées localement sur votre appareil en utilisant la technologie de stockage local sécurisé. Nous n\'envoyons ni ne partageons aucune de vos données personnelles avec des serveurs externes ou des tiers.',
    localStorage: 'Stockage Local',
    importantNote: 'Note Importante :',
    localStorageText: 'Toutes vos données sont stockées localement dans votre navigateur. Si vous effacez les données du navigateur ou désinstallez l\'application, vous perdrez toutes vos données sauvegardées. Nous recommandons de sauvegarder vos données importantes.',
    thirdParties: 'Tiers',
    thirdPartiesText: 'Nous ne partageons pas vos données avec des tiers. L\'application fonctionne de manière indépendante et ne nécessite pas de connexion Internet pour les fonctions de base.',
    userRights: 'Droits de l\'Utilisateur',
    userRightsText: 'En tant qu\'utilisateur, vous avez le droit de :',
    userRight1: 'Accéder à toutes vos données sauvegardées',
    userRight2: 'Modifier ou supprimer vos données',
    userRight3: 'Exporter vos données (via les fonctionnalités du navigateur)',
    userRight4: 'Arrêter d\'utiliser l\'application à tout moment',
    lastUpdated: 'Dernière Mise à Jour',
    lastUpdatedDate: '20 août 2024',
    contactInfo: 'Pour les demandes : Contactez-nous via l\'application',
    
    // Water Calculator
    waterCalculator: 'Calculateur d\'Eau',
    waterCalculatorDesc: 'Calculez votre apport quotidien en eau basé sur votre poids et activité physique',
    waterNeedsCalculator: 'Calculateur de Vos Besoins en Eau',
    waterNeedsCalculatorDesc: 'Entrez votre poids et heures d\'exercice pour calculer vos besoins quotidiens en eau',
    weightKg: 'Poids (kg)',
    enterWeight: 'Entrez votre poids',
    dailyExerciseHours: 'Heures d\'Exercice Quotidiennes',
    enterExerciseHours: 'Entrez les heures d\'exercice',
    reset: 'Réinitialiser',
    yourDailyWaterIntake: 'Votre Apport Quotidien en Eau',
    ml: 'ml',
    glassesApprox: 'verres (250ml chacun)',
    note: 'Note :',
    waterNote: 'Ceci est une estimation. Vous pourriez avoir besoin de plus d\'eau par temps chaud ou en cas de maladie.',
    urineColorGuide: 'Guide de Couleur d\'Urine',
    urineColorGuideDesc: 'Vérifiez votre état d\'hydratation grâce à la couleur de l\'urine',
    clearVeryLightYellow: 'Claire/Jaune Très Clair',
    excellentOptimalHydration: 'Excellent - Hydratation Optimale',
    lightYellow: 'Jaune Clair',
    goodAdequateHydration: 'Bon - Hydratation Adéquate',
    mediumYellow: 'Jaune Moyen',
    drinkMoreWater: 'Buvez Plus d\'Eau',
    darkYellow: 'Jaune Foncé',
    mildDehydration: 'Déshydratation Légère - Buvez de l\'Eau Maintenant',
    brownOrange: 'Brun/Orange',
    severeDehydration: 'Déshydratation Sévère - Consultez un Médecin',
    hydrationTips: 'Conseils pour une Hydratation Optimale :',
    hydrationTip1: 'Buvez de l\'eau tout au long de la journée',
    hydrationTip2: 'Buvez plus avant, pendant et après l\'exercice',
    hydrationTip3: 'Augmentez l\'apport par temps chaud',
    hydrationTip4: 'Limitez la caféine et l\'alcool',
    invalidWeight: 'Veuillez entrer un poids valide (1-500 kg)',
    invalidExercise: 'Veuillez entrer des heures d\'exercice valides (0-24 heures)'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');
  const isRTL = language === 'ar';

  useEffect(() => {
    const savedLanguage = localStorage.getItem('sehati-language') as Language;
    if (savedLanguage && ['ar', 'en', 'fr'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('sehati-language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language]?.[key as keyof typeof translations[typeof language]] || key;
  };

  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};