import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    appName: 'قياساتي',
    calorieCalculator: 'حاسبة السعرات الحرارية',
    bodyMeasurements: 'قياسات الجسم',
    cardioConverter: 'محول الكارديو',
    age: 'العمر',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    weight: 'الوزن (كيلو)',
    height: 'الطول (سم)',
    activityLevel: 'مستوى النشاط',
    sedentary: 'قليل الحركة',
    lightlyActive: 'نشاط خفيف',
    moderatelyActive: 'نشاط متوسط',
    veryActive: 'نشاط عالي',
    extraActive: 'نشاط عالي جداً',
    calculate: 'احسب',
    bmr: 'معدل الأيض الأساسي',
    tdee: 'إجمالي استهلاك الطاقة اليومي',
    calories: 'سعرة حرارية',
    startTracking: 'ابدأ التتبع',
    yourHealthGuide: 'دليلك الصحي الشامل',
    trackCalories: 'لحساب السعرات الحرارية وتتبع قياسات الجسم وتحويل السعرات لدقائق التمارين',
    
    // My Items
    myItems: 'أغراضي',
    myItemsDesc: 'تحقق من أغراض التمرين قبل الذهاب وبعد العودة',
    exploreItems: 'استكشف أغراضي',
    beforeWorkout: 'قبل التمرين',
    afterWorkout: 'بعد التمرين',
    addNewItem: 'إضافة غرض جديد',
    itemName: 'اسم الغرض',
    selectIcon: 'اختر أيقونة',
    add: 'إضافة',
    cancel: 'إلغاء',
    delete: 'حذف',
    checkAll: 'تحقق من الكل',
    uncheckAll: 'إلغاء تحديد الكل',
    noItemsYet: 'لا توجد أغراض بعد',
    addFirstItem: 'أضف أول غرض لك',
    workoutReminder: 'تذكير التمرين',
    enableNotifications: 'تفعيل الإشعارات',
    setWorkoutTime: 'حدد وقت التمرين',
    reminderBefore: 'تذكير قبل التمرين (دقيقة)',
    reminderAfter: 'تذكير بعد التمرين (دقيقة)',
    save: 'حفظ',
    beforeWorkoutDesc: 'تأكد من جميع أغراضك قبل الذهاب للتمرين',
    afterWorkoutDesc: 'تأكد من استرداد جميع أغراضك بعد التمرين',
    
    // Body Measurements
    neck: 'الرقبة (سم)',
    shoulders: 'الأكتاف (سم)',
    chest: 'الصدر (سم)',
    rightArm: 'الذراع الأيمن (سم)',
    leftArm: 'الذراع الأيسر (سم)',
    abdomen: 'البطن (سم)',
    waist: 'الخصر (سم)',
    rightThigh: 'الفخذ الأيمن (سم)',
    leftThigh: 'الفخذ الأيسر (سم)',
    rightLeg: 'الساق الأيمن (سم)',
    leftLeg: 'الساق الأيسر (سم)',
    addMeasurement: 'أضف قياس جديد',
    saveMeasurement: 'احفظ القياس',
    measurementSaved: 'تم حفظ القياس بنجاح!',
    noMeasurements: 'لا توجد قياسات محفوظة',
    measurementHistory: 'تاريخ القياسات',
    viewProgress: 'عرض التقدم',
    date: 'التاريخ',
    measurement: 'القياس',
    progress: 'التقدم',
    cm: 'سم',
    
    // Bodybuilding specific measurements
    arms: 'الذراعين (سم)',
    calves: 'السمانة (سم)', 
    thighs: 'الفخذين (سم)',
    back: 'الظهر (سم)',
    
    // New measurement type labels
    selectMeasurementType: 'اختر نوع القياسات',
    generalMeasurements: 'قياسات عامة',
    generalMeasurementsDesc: 'لإنقاص الوزن والمتابعة العامة',
    bodybuildingMeasurements: 'قياسات كمال الأجسام', 
    bodybuildingMeasurementsDesc: 'للاعبي كمال الأجسام والبناء العضلي',
    generalMeasurementsTitle: 'القياسات العامة',
    bodybuildingMeasurementsTitle: 'قياسات كمال الأجسام',
    measurementPlaceholder: 'سم',
    bodybuildingType: 'كمال أجسام',
    generalType: 'عامة',
    measurementCount: 'قياسات',
    trackBodyMeasurements: 'تتبع قياسات الجسم',
    trackBodyMeasurementsDesc: 'سجل وتتبع قياساتك في جميع المناطق الرئيسية',
    
    // Cardio Converter
    caloriesInput: 'عدد السعرات المراد حرقها',
    exerciseType: 'نوع التمرين',
    running: 'الجري',
    cycling: 'ركوب الدراجة',
    swimming: 'السباحة',
    walking: 'المشي',
    jumpingRope: 'نط الحبل',
    rowing: 'التجديف',
    convert: 'تحويل',
    timeNeeded: 'الوقت المطلوب',
    minutes: 'دقيقة',
    selectExercise: 'اختر نوع التمرين',
    enterCalories: 'أدخل عدد السعرات',
    backToHome: 'العودة للرئيسية',
    explore: 'استكشف',
    getStarted: 'ابدأ الآن',
    trackMyHealth: 'تتبع صحتي',
    
    // Weekly Program
    weeklyProgram: 'البرنامج الأسبوعي',
    createProgram: 'إنشاء برنامج',
    myPrograms: 'برامجي',
    programName: 'اسم البرنامج',
    dayOfWeek: 'يوم الأسبوع',
    exerciseName: 'اسم التمرين',
    sets: 'المجموعات',
    reps: 'التكرارات',
    exerciseWeight: 'الوزن',
    notes: 'ملاحظات',
    addExercise: 'إضافة تمرين',
    saveProgram: 'حفظ البرنامج',
    programSaved: 'تم حفظ البرنامج بنجاح!',
    noPrograms: 'لا توجد برامج محفوظة',
    editProgram: 'تعديل البرنامج',
    deleteProgram: 'حذف البرنامج',
    confirmDelete: 'هل أنت متأكد من حذف هذا البرنامج؟',
    sunday: 'الأحد',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    saturday: 'السبت',
    rest: 'راحة',
    
    // Wake-up Challenge
    wakeUpChallenge: 'تحدي الاستيقاظ',
    setupChallenge: 'إعداد التحدي',
    tracking: 'التتبع',
    statistics: 'الإحصائيات',
    wakeUpTime: 'وقت الاستيقاظ',
    challengeDuration: 'مدة التحدي (أيام)',
    startChallenge: 'ابدأ التحدي',
    activeChallenge: 'التحدي النشط',
    targetWakeTime: 'وقت الاستيقاظ المحدد',
    today: 'اليوم',
    target: 'الهدف',
    wokeUp: 'الاستيقاظ',
    imAwake: 'أنا استيقظت',
    done: 'تم',
    pending: 'في الانتظار',
    endChallenge: 'إنهاء التحدي',
    dailyRecords: 'سجل الأيام',
    noActiveChallenge: 'لا يوجد تحدي نشط',
    setupNewChallenge: 'ابدأ تحدي جديد لتتبع استيقاظك',
    totalDays: 'إجمالي الأيام',
    successfulDays: 'أيام ناجحة',
    successRate: 'معدل النجاح',
    achievementLevel: 'مستوى الإنجاز',
    excellent: 'ممتاز',
    good: 'جيد',
    average: 'متوسط',
    needsImprovement: 'يحتاج تحسين',
    challengeSummary: 'ملخص التحدي',
    challengePeriod: 'فترة التحدي',
    days: 'أيام',
    overallProgress: 'التقدم الإجمالي',
    noStatistics: 'لا توجد إحصائيات',
    completeChallenge: 'أكمل تحدي للحصول على الإحصائيات',
    challengeStarted: 'بدأ التحدي!',
    challengeStartedDesc: 'تم بدء تحدي الاستيقاظ بنجاح',
    recorded: 'تم التسجيل!',
    recordedDesc: 'تم تسجيل وقت استيقاظك بنجاح',
    challengeEnded: 'انتهى التحدي!',
    challengeEndedDesc: 'انتهى التحدي، تحقق من إحصائياتك',
    
    // Terms and Privacy
    termsAndPrivacy: 'الشروط والخصوصية',
    termsAndPrivacyDesc: 'اقرأ شروط الاستخدام وسياسة الخصوصية للتطبيق',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    acceptanceOfTerms: 'قبول الشروط',
    acceptanceOfTermsText: 'باستخدام تطبيق "qiyasat"، فإنك توافق على الالتزام بجميع الشروط والأحكام المذكورة هنا. إذا كنت لا توافق على أي من هذه الشروط، يرجى عدم استخدام التطبيق.',
    serviceDescription: 'وصف الخدمة',
    serviceDescriptionText: 'تطبيق "qiyasat" هو أداة مساعدة لتتبع الصحة واللياقة البدنية تتضمن حاسبة السعرات الحرارية، قياسات الجسم، محول الكارديو، البرامج الأسبوعية، وتتبع الأغراض الرياضية.',
    userResponsibilities: 'مسؤوليات المستخدم',
    userResponsibilitiesText: 'كمستخدم لهذا التطبيق، فإنك توافق على:',
    userResp1: 'استخدام التطبيق للأغراض الشخصية والصحية فقط',
    userResp2: 'عدم مشاركة معلوماتك الشخصية مع أطراف ثالثة',
    userResp3: 'الحفاظ على دقة المعلومات التي تدخلها',
    userResp4: 'عدم استخدام التطبيق لأغراض غير قانونية أو ضارة',
    limitations: 'القيود والحدود',
    limitationsText: 'هذا التطبيق مخصص للأغراض المعلوماتية والتتبع الشخصي فقط. النتائج المقدمة هي تقديرات عامة وقد لا تناسب جميع الحالات الصحية الفردية.',
    medicalDisclaimer: 'إخلاء المسؤولية الطبية',
    important: 'مهم:',
    medicalDisclaimerText: 'هذا التطبيق ليس بديلاً عن الاستشارة الطبية المهنية أو التشخيص أو العلاج. استشر دائماً طبيبك أو مختص الرعاية الصحية قبل البدء في أي برنامج تمارين أو نظام غذائي جديد.',
    modifications: 'التعديلات',
    modificationsText: 'نحتفظ بالحق في تعديل هذه الشروط في أي وقت. سيتم إشعار المستخدمين بأي تغييرات جوهرية من خلال التطبيق.',
    dataCollection: 'جمع البيانات',
    dataCollectionText: 'نحن نجمع ونخزن البيانات التالية محلياً على جهازك فقط:',
    dataType1: 'المعلومات الشخصية (العمر، الجنس، الوزن، الطول)',
    dataType2: 'قياسات الجسم والتقدم',
    dataType3: 'تفضيلات التطبيق (اللغة، السمة)',
    dataType4: 'سجلات التمارين والأنشطة',
    dataUsage: 'استخدام البيانات',
    dataUsageText: 'نستخدم بياناتك لـ:',
    dataUsage1: 'حساب السعرات الحرارية والقيم الغذائية',
    dataUsage2: 'تتبع تقدمك الشخصي',
    dataUsage3: 'تخصيص تجربة التطبيق',
    dataUsage4: 'حفظ تفضيلاتك وإعداداتك',
    dataSecurity: 'أمان البيانات',
    dataSecurityText: 'جميع بياناتك محفوظة محلياً على جهازك باستخدام تقنية Local Storage الآمنة. نحن لا نرسل أو نشارك أي من بياناتك الشخصية مع خوادم خارجية أو أطراف ثالثة.',
    localStorage: 'التخزين المحلي',
    importantNote: 'ملاحظة مهمة:',
    localStorageText: 'جميع بياناتك محفوظة محلياً على متصفحك. إذا قمت بمسح بيانات المتصفح أو إلغاء تثبيت التطبيق، ستفقد جميع بياناتك المحفوظة. ننصح بعمل نسخة احتياطية من بياناتك المهمة.',
    thirdParties: 'الأطراف الثالثة',
    thirdPartiesText: 'نحن لا نشارك بياناتك مع أي أطراف ثالثة. التطبيق يعمل بشكل مستقل ولا يتطلب اتصالاً بالإنترنت للوظائف الأساسية.',
    userRights: 'حقوق المستخدم',
    userRightsText: 'كمستخدم، لديك الحق في:',
    userRight1: 'الوصول إلى جميع بياناتك المحفوظة',
    userRight2: 'تعديل أو حذف أي من بياناتك',
    userRight3: 'تصدير بياناتك (عبر ميزات المتصفح)',
    userRight4: 'إيقاف استخدام التطبيق في أي وقت',
    lastUpdated: 'آخر تحديث',
    lastUpdatedDate: '20 أغسطس 2024',
    contactInfo: 'للاستفسارات: تواصل معنا عبر التطبيق'
  },
  en: {
    appName: 'QiyasaT',
    calorieCalculator: 'Calorie Calculator',
    bodyMeasurements: 'Body Measurements',
    cardioConverter: 'Cardio Converter',
    age: 'Age',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    weight: 'Weight (kg)',
    height: 'Height (cm)',
    activityLevel: 'Activity Level',
    sedentary: 'Sedentary (little/no exercise)',
    lightlyActive: 'Lightly active (light exercise)',
    moderatelyActive: 'Moderately active (moderate exercise)',
    veryActive: 'Very active (hard exercise)',
    extraActive: 'Extra active (very hard exercise)',
    calculate: 'Calculate',
    bmr: 'Basal Metabolic Rate',
    tdee: 'Total Daily Energy Expenditure',
    calories: 'calories',
    startTracking: 'Start Tracking',
    yourHealthGuide: 'Your Complete Health Guide',
    trackCalories: 'Calculate calories, track body measurements, and convert calories to exercise minutes',
    
    // My Items
    myItems: 'My Items',
    myItemsDesc: 'Check workout items before going and after returning',
    exploreItems: 'Explore My Items',
    beforeWorkout: 'Before Workout',
    afterWorkout: 'After Workout',
    addNewItem: 'Add New Item',
    itemName: 'Item Name',
    selectIcon: 'Select Icon',
    add: 'Add',
    cancel: 'Cancel',
    delete: 'Delete',
    checkAll: 'Check All',
    uncheckAll: 'Uncheck All',
    noItemsYet: 'No items yet',
    addFirstItem: 'Add your first item',
    workoutReminder: 'Workout Reminder',
    enableNotifications: 'Enable Notifications',
    setWorkoutTime: 'Set Workout Time',
    reminderBefore: 'Reminder before workout (minutes)',
    reminderAfter: 'Reminder after workout (minutes)',
    save: 'Save',
    beforeWorkoutDesc: 'Make sure you have all your items before going to workout',
    afterWorkoutDesc: 'Make sure to retrieve all your items after workout',
    
    // Body Measurements
    neck: 'Neck (cm)',
    shoulders: 'Shoulders (cm)',
    chest: 'Chest (cm)',
    rightArm: 'Right Arm (cm)',
    leftArm: 'Left Arm (cm)',
    abdomen: 'Abdomen (cm)',
    waist: 'Waist (cm)',
    rightThigh: 'Right Thigh (cm)',
    leftThigh: 'Left Thigh (cm)',
    rightLeg: 'Right Leg (cm)',
    leftLeg: 'Left Leg (cm)',
    addMeasurement: 'Add New Measurement',
    saveMeasurement: 'Save Measurement',
    measurementSaved: 'Measurement saved successfully!',
    noMeasurements: 'No measurements saved',
    measurementHistory: 'Measurement History',
    viewProgress: 'View Progress',
    date: 'Date',
    measurement: 'Measurement',
    progress: 'Progress',
    cm: 'cm',
    
    // Bodybuilding specific measurements
    arms: 'Arms (cm)',
    calves: 'Calves (cm)',
    thighs: 'Thighs (cm)', 
    back: 'Back (cm)',
    
    // New measurement type labels
    selectMeasurementType: 'Select Measurement Type',
    generalMeasurements: 'General Measurements',
    generalMeasurementsDesc: 'For weight loss and general tracking',
    bodybuildingMeasurements: 'Bodybuilding Measurements',
    bodybuildingMeasurementsDesc: 'For bodybuilders and muscle building',
    generalMeasurementsTitle: 'General Measurements',
    bodybuildingMeasurementsTitle: 'Bodybuilding Measurements',
    measurementPlaceholder: 'cm',
    bodybuildingType: 'Bodybuilding',
    generalType: 'General',
    measurementCount: 'measurements',
    trackBodyMeasurements: 'Track Body Measurements',
    trackBodyMeasurementsDesc: 'Record and track your measurements in all key areas',
    
    // Cardio Converter
    caloriesInput: 'Calories to burn',
    exerciseType: 'Exercise type',
    running: 'Running',
    cycling: 'Cycling',
    swimming: 'Swimming',
    walking: 'Walking',
    jumpingRope: 'Jumping rope',
    rowing: 'Rowing',
    convert: 'Convert',
    timeNeeded: 'Time needed',
    minutes: 'minutes',
    selectExercise: 'Select exercise type',
    enterCalories: 'Enter calories',
    backToHome: 'Back to Home',
    explore: 'Explore',
    getStarted: 'Get Started',
    trackMyHealth: 'Track My Health',
    
    // Weekly Program
    weeklyProgram: 'Weekly Program',
    createProgram: 'Create Program',
    myPrograms: 'My Programs',
    programName: 'Program Name',
    dayOfWeek: 'Day of Week',
    exerciseName: 'Exercise Name',
    sets: 'Sets',
    reps: 'Reps',
    exerciseWeight: 'Weight',
    notes: 'Notes',
    addExercise: 'Add Exercise',
    saveProgram: 'Save Program',
    programSaved: 'Program saved successfully!',
    noPrograms: 'No programs saved',
    editProgram: 'Edit Program',
    deleteProgram: 'Delete Program',
    confirmDelete: 'Are you sure you want to delete this program?',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    rest: 'Rest',
    
    // Wake-up Challenge
    wakeUpChallenge: 'Wake-up Challenge',
    setupChallenge: 'Setup Challenge',
    tracking: 'Tracking',
    statistics: 'Statistics',
    wakeUpTime: 'Wake-up Time',
    challengeDuration: 'Challenge Duration (days)',
    startChallenge: 'Start Challenge',
    activeChallenge: 'Active Challenge',
    targetWakeTime: 'Target wake-up time',
    today: 'Today',
    target: 'Target',
    wokeUp: 'Woke up',
    imAwake: 'I\'m Awake',
    done: 'Done',
    pending: 'Pending',
    endChallenge: 'End Challenge',
    dailyRecords: 'Daily Records',
    noActiveChallenge: 'No Active Challenge',
    setupNewChallenge: 'Start a new challenge to track your wake-up times',
    totalDays: 'Total Days',
    successfulDays: 'Successful Days',
    successRate: 'Success Rate',
    achievementLevel: 'Achievement Level',
    excellent: 'Excellent',
    good: 'Good',
    average: 'Average',
    needsImprovement: 'Needs Improvement',
    challengeSummary: 'Challenge Summary',
    challengePeriod: 'Challenge Period',
    days: 'days',
    overallProgress: 'Overall Progress',
    noStatistics: 'No Statistics Available',
    completeChallenge: 'Complete a challenge to see statistics',
    challengeStarted: 'Challenge Started!',
    challengeStartedDesc: 'Wake-up challenge started successfully',
    recorded: 'Recorded!',
    recordedDesc: 'Your wake-up time has been recorded successfully',
    challengeEnded: 'Challenge Ended!',
    challengeEndedDesc: 'Challenge ended, check your statistics',
    
    // Terms and Privacy
    termsAndPrivacy: 'Terms & Privacy',
    termsAndPrivacyDesc: 'Read the terms of service and privacy policy for the app',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    acceptanceOfTerms: 'Acceptance of Terms',
    acceptanceOfTermsText: 'By using the "Sehati" app, you agree to comply with all the terms and conditions mentioned here. If you do not agree to any of these terms, please do not use the app.',
    serviceDescription: 'Service Description',
    serviceDescriptionText: 'The "Sehati" app is a health and fitness tracking tool that includes calorie calculator, body measurements, cardio converter, weekly programs, and sports items tracking.',
    userResponsibilities: 'User Responsibilities',
    userResponsibilitiesText: 'As a user of this app, you agree to:',
    userResp1: 'Use the app for personal and health purposes only',
    userResp2: 'Not share your personal information with third parties',
    userResp3: 'Maintain accuracy of the information you enter',
    userResp4: 'Not use the app for illegal or harmful purposes',
    limitations: 'Limitations',
    limitationsText: 'This app is intended for informational and personal tracking purposes only. The results provided are general estimates and may not suit all individual health conditions.',
    medicalDisclaimer: 'Medical Disclaimer',
    important: 'Important:',
    medicalDisclaimerText: 'This app is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your doctor or healthcare professional before starting any new exercise program or diet.',
    modifications: 'Modifications',
    modificationsText: 'We reserve the right to modify these terms at any time. Users will be notified of any material changes through the app.',
    dataCollection: 'Data Collection',
    dataCollectionText: 'We collect and store the following data locally on your device only:',
    dataType1: 'Personal information (age, gender, weight, height)',
    dataType2: 'Body measurements and progress',
    dataType3: 'App preferences (language, theme)',
    dataType4: 'Exercise and activity records',
    dataUsage: 'Data Usage',
    dataUsageText: 'We use your data to:',
    dataUsage1: 'Calculate calories and nutritional values',
    dataUsage2: 'Track your personal progress',
    dataUsage3: 'Customize the app experience',
    dataUsage4: 'Save your preferences and settings',
    dataSecurity: 'Data Security',
    dataSecurityText: 'All your data is stored locally on your device using secure Local Storage technology. We do not send or share any of your personal data with external servers or third parties.',
    localStorage: 'Local Storage',
    importantNote: 'Important Note:',
    localStorageText: 'All your data is stored locally in your browser. If you clear browser data or uninstall the app, you will lose all your saved data. We recommend backing up your important data.',
    thirdParties: 'Third Parties',
    thirdPartiesText: 'We do not share your data with any third parties. The app operates independently and does not require internet connection for basic functions.',
    userRights: 'User Rights',
    userRightsText: 'As a user, you have the right to:',
    userRight1: 'Access all your saved data',
    userRight2: 'Modify or delete any of your data',
    userRight3: 'Export your data (via browser features)',
    userRight4: 'Stop using the app at any time',
    lastUpdated: 'Last Updated',
    lastUpdatedDate: 'August 20, 2024',
    contactInfo: 'For inquiries: Contact us through the app'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');
  const isRTL = language === 'ar';

  useEffect(() => {
    const savedLanguage = localStorage.getItem('sehati-language') as Language;
    if (savedLanguage && ['ar', 'en'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('sehati-language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ar']] || key;
  };

  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};